# This file configures the hello-world app which serves public web traffic.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: statutes-rest-ca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statutes-rest-ca
  template:
    metadata:
      labels:
        app: statutes-rest-ca
    spec:
      containers:
      - name: statutes-rest-ca-app
        # Replace $GCLOUD_PROJECT with your project ID
        image: gcr.io/legalservices/statutes-rest-ca
        env:
          - name: PORT
            value: "8090"
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8090
        volumeMounts:
        - name: opcastorage-mount
          mountPath: /opcastorage
          readOnly: true
      volumes:
      - name: opcastorage-mount
        persistentVolumeClaim:
          claimName: opcastorage-pvc
          readOnly: true
