FROM registry.redhat.io/openjdk/openjdk-11-rhel7
VOLUME /tmp
VOLUME /CaliforniaStatutes
ENV californiastatutesloc=/CaliforniaStatutes
COPY target/*.jar app.jar
EXPOSE 8090
CMD [ "java", "-XX:+UseContainerSupport", "-jar", "app.jar" ]
