apiVersion: v1
kind: PersistentVolume
metadata:
  name: statutes-rest-ca-pv
spec:
  storageClassName: "opca-storageclass"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  claimRef:
    namespace: default
    name: statutes-rest-ca-pvc
  gcePersistentDisk:
    pdName: statutes-rest-ca-disk
    fsType: ext4
    readOnly: true