apiVersion: v1
kind: PersistentVolume
metadata:
  name: opcastorage-pv
spec:
  storageClassName: "opcastorage-class"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  claimRef:
    namespace: default
    name: opcastorage-pvc
  gcePersistentDisk:
    pdName: opcastorage-disk
    fsType: ext4
    readOnly: true