# This file configures the hello-world app which serves public web traffic.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guidedsearchweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guidedsearchweb
  template:
    metadata:
      labels:
        app: guidedsearchweb
    spec:
      containers:
      - name: guidedsearchweb-app
        # Replace $GCLOUD_PROJECT with your project ID
        image: gcr.io/legalservices/guidedsearchweb
        env:
          - name: PORT
            value: "8092"
          - name: statutesrestca
            value: "http://statutesrestca-service:8090/"
        # This app listens on port 8092 for web traffic by default.
        ports:
        - containerPort: 8092
          name: actuator
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: actuator
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: actuator
        volumeMounts:
        - name: opcastorage-mount
          mountPath: /opcastorage
          readOnly: true
      volumes:
      - name: opcastorage-mount
        persistentVolumeClaim:
          claimName: opcastorage-pvc
          readOnly: true
         