# This file configures the hello-world app which serves public web traffic.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opinionrestca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opinionrestca
  template:
    metadata:
      labels:
        app: opinionrestca
    spec:
      containers:
      - name: opinionrestca-app
        # Replace $GCLOUD_PROJECT with your project ID
        image: gcr.io/legalservices/opinionrestca
        env:
          - name: PORT
            value: "8091"
          - name: database-url
            value: "mysql://mysql-opca-vm:3306/"
          - name: database-user
            valueFrom:
              secretKeyRef:
                name: mysqldb
                key: database-user
          - name: database-name
            valueFrom:
              secretKeyRef:
                name: mysqldb
                key: database-name
          - name: database-password
            valueFrom:
              secretKeyRef:
                name: mysqldb
                key: database-password
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8091
